CREATE TABLE `npms`.`new_table` (
  `ID` INT NOT NULL AUTO_INCREMENT,
   `Action` VARCHAR(45) NULL,
  `User` VARCHAR(45) NULL,
  `Rol` VARCHAR(45) NULL,
  `For_User` VARCHAR(45) NULL,
 `Date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP  
   ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE);